def get_d4j_bug_list():
    # Defects4j
    d4j = []
    d4j.append("Chart-2")
    d4j.append("Chart-4")
    d4j.append("Chart-14")
    d4j.append("Chart-16")
    d4j.append("Cli-5")
    d4j.append("Cli-30")
    d4j.append("Closure-2")
    d4j.append("Closure-171")
    d4j.append("Codec-5")
    d4j.append("Codec-13")
    d4j.append("Codec-17")
    d4j.append("Csv-4")
    d4j.append("Csv-9")
    d4j.append("Csv-11")
    d4j.append("Gson-6")
    d4j.append("Gson-9")
    d4j.append("JacksonCore-8")
    d4j.append("JacksonDatabind-3")
    d4j.append("JacksonDatabind-13")
    d4j.append("JacksonDatabind-36")
    d4j.append("JacksonDatabind-80")
    d4j.append("JacksonDatabind-93")
    d4j.append("JacksonDatabind-95")
    d4j.append("JacksonDatabind-107")
    d4j.append("Jsoup-8")
    d4j.append("Jsoup-22")
    d4j.append("Jsoup-26")
    d4j.append("Jsoup-66")
    d4j.append("Jsoup-89")
    d4j.append("JxPath-1")
    d4j.append("Lang-20")
    d4j.append("Lang-33")
    d4j.append("Lang-39")
    d4j.append("Lang-47")
    d4j.append("Lang-57")
    d4j.append("Math-4")
    d4j.append("Math-70")
    d4j.append("Math-79")
    d4j.append("Mockito-18")
    d4j.append("Mockito-38")

    return d4j